site_name: مستندات فنی دیپلوکا

repo_url: https://github.com/deploca/docs-fa
repo_name: deploca/docs-fa

theme:
  name: material
  language: fa
  font:
    text: IRANSans
    code: Roboto Mono
  palette:
    scheme: default
    primary: indigo
    accent: pink

extra_css:
  - https://deploca.com/fonts/iransans/css/iransans.css

extra:
  social:
    - name: Deploca on GitHub
      icon: fontawesome/brands/github
      link: https://github.com/deploca
    - name: Deploca on LinkedIn
      icon: fontawesome/brands/linkedin
      link: https://github.com/deploca
